---
version: "2.1"
services:
  webtop:
    image: re1r0h/ubuntu:latest
    #image: ghcr.io/linuxserver/webtop:ubuntu-mate (this is base image)
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Columbus
    volumes:
      - /home/maanav0114/ubuntu/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 4020:3000
    shm_size: "2gb" #optional
    restart: unless-stopped
    privileged: true
